### ISSUE TITLE
Mac: Launcher Errors out when trying to open the Minecraft page.

### ISSUE THREAD

**Issue by CodaKidGit** [ClarisoftTechnologies/codakidLauncherRelease#28]
The Mac version of the launcher displayed the following error when trying to open the Minecraft page for the first time:
![image](https://user-images.githubusercontent.com/3650603/124006668-6439ea80-d98f-11eb-9c8c-ca75e5382c4a.png)

Steps to reproduce:
1. Install the launcher on Mac.
2. Install for all users.
3. Open the launcher
4. Click the Minecraft tab

**Comment by CodaKidGit** [comment]
The permissions:
```
renatoc@Renatos-MacBook-Pro /Users]ls -la
drwxr-xr-x+ 84 renatoc staff  2688 Jul 28 13:50 renatoc
renatoc@Renatos-MacBook-Pro ~]ls -la
drwxr-xr-x     9 renatoc staff       288 Jul 28 13:46  Applications
renatoc@Renatos-MacBook-Pro ~/Applications]ls -la
drwxr-xr-x   3 renatoc staff   96 Jul 28 13:46  CodaKid.app
```
The logs from a computer that ran into this issue.

```

renatoc@Renatos-MacBook-Pro ~/Applications/CodaKid.app/Contents/MacOS]./CodaKid
get icon /Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/assets/icons/favicon.png
(node:11194) UnhandledPromiseRejectionWarning: Error: Unsupported macOS version: 20.5.0
    at getMacOsVersion (/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/os_modules/common/helpers/operatingSystemHelpers.js:57:19)
    at getOperatingSystemVersion (/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/os_modules/common/helpers/operatingSystemHelpers.js:19:20)
    at App.createWindow (/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/main/index.js:107:36)
    at App.emit (events.js:327:22)
(Use `CodaKid --trace-warnings ...` to show where the warning was created)
(node:11194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11194) UnhandledPromiseRejectionWarning: Error: Unsupported macOS version: 20.5.0
    at getMacOsVersion (/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/os_modules/common/helpers/operatingSystemHelpers.js:57:19)
    at getOperatingSystemVersion (/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/os_modules/common/helpers/operatingSystemHelpers.js:19:20)
    at IpcMainImpl.<anonymous> (/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app.asar/src/main/index.js:193:36)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
(node:11194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Checking for update
Error: Error: ENOENT: no such file or directory, open '/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app-update.yml'
(node:11194) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/renatoc/Applications/CodaKid.app/Contents/Resources/app-update.yml'
(node:11194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```
